# Mapping arrays to Neopixel leds

To build more complicated applications using neopixel lights I needed to be able to cast RGB values to a dataframe or numpy array. This will enable me to program the LEDs using more complicated stats packages. 

**note** I'm writing this jupyter notebook, and not on a raspbery pi. The module `ledArray` will run on my Raspbery PI 4 with no problem but the `neopixel` and `board` module isn't on my VM. 

The trick is to build a matrix of the RGB values that you want and then flatten it into a NeoPixel array. A `NeoPixel` is an array of RGB values so you can manipulate it the same way you would a numpy array. 

In [1]:
#You'll need these packages to execute the code on an RPi
#import board
#import neopixel

#other more standard libraries
import numpy as np
import pandas as pd

#my libraries
import ledArray as led

I'm using a 60 pixel array, cut and diced into 6 slices (rows) of 10 leds (columns). I want to put this into a grid. I also am going to run this from a single GPIO pin

I would normally run the line:
`pixels = neopixel.NeoPixel(board.D18, 60)` to fire up the board. Then `pixels[0] = (100,100,100)` or something to turn that light on. 

In [2]:
leds = led.dummy_pixels(60)

leds

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

Creating an array of `dummpy_pixels` allows me to shape that into a dataframe. Which I can perform more complicated functions on. 

In [3]:
shape = (6,10)

df = led.leds_to_df(leds,shape)
df

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59

Then you can use tools like `.loc` and other functions to get the lists of leds that you will activate. 

In [4]:
coord = [1,1]
p = df.loc[coord[0],coord[1]]
p

#the pin could activate with this.
#pixels[p] = (100,100,100) 

11

ok how about a little box: 

In [5]:
p = df.loc[2:3,2:3].values.flatten()


def lightup(n,value=(100,100,100)):
    pixels[n] = value
#Light these up with
#[lightup(n) for n in p]

p

array([22, 23, 32, 33])

Now let's animate that box my moving it across the grid. 

In [7]:
x = 0
y = 0

p = []
for i in range(5):
    print (x,y)
    x=x+i
    y=y+i
    p.append(df.loc[x:x+1,y:y+1].values.flatten())

#You'll need an array to turn the lights off after. 
#[[lightup(n) for n in p] for n in p]
p

0 0
0 0
1 1
3 3
6 6


[array([ 0,  1, 10, 11]),
 array([11, 12, 21, 22]),
 array([33, 34, 43, 44]),
 array([], dtype=int64),
 array([], dtype=int64)]

Notice that `.loc` doesn't raise an error, it just returns blank values. That's convinient as I won't have to worry if my box rolls off screen. 

Assigning colors randomly is easy as well. 

In [8]:
def random_color():
    x = np.random.randint(0,255),np.random.randint(0,255),np.random.randint(0,255)
    return x
    
[random_color() for i in range(3)]

[(119, 250, 168), (57, 199, 232), (142, 92, 229)]

In [9]:
import sklearn

ModuleNotFoundError: No module named 'sklearn'